// Command control-plane is the helmdeck Golang control plane.
//
// It serves the REST API, the embedded React UI, the AI gateway, the MCP
// registry, the credential vault, and orchestrates ephemeral browser session
// containers via the SessionRuntime interface (see ADR 002, 009).
package main

import (
	"context"
	"database/sql"
	"errors"
	"flag"
	"fmt"
	"log/slog"
	"net/http"
	"net/url"
	"os"
	"os/signal"
	"path/filepath"
	"strings"
	"syscall"
	"time"

	"github.com/tosin2013/helmdeck/internal/api"
	"github.com/tosin2013/helmdeck/internal/audit"
	"github.com/tosin2013/helmdeck/internal/auth"
	"github.com/tosin2013/helmdeck/internal/gateway"
	"github.com/tosin2013/helmdeck/internal/inject"
	"github.com/tosin2013/helmdeck/internal/keystore"
	"github.com/tosin2013/helmdeck/internal/marketplace"
	"github.com/tosin2013/helmdeck/internal/mcp"
	"github.com/tosin2013/helmdeck/internal/packs"
	"github.com/tosin2013/helmdeck/internal/packs/builtin"
	"strconv"

	"github.com/tosin2013/helmdeck/internal/security"
	"github.com/tosin2013/helmdeck/internal/session"
	dockerrt "github.com/tosin2013/helmdeck/internal/session/docker"
	"github.com/tosin2013/helmdeck/internal/store"
	"github.com/tosin2013/helmdeck/internal/telemetry"
	"github.com/tosin2013/helmdeck/internal/vault"
	"github.com/tosin2013/helmdeck/internal/vision"
)

var (
	version = "dev"     // overridden at build time via -ldflags
	commit  = "unknown" // overridden at build time via -ldflags
)

func main() {
	addr := flag.String("addr", envOr("HELMDECK_ADDR", ":3000"), "listen address")
	dbPath := flag.String("db", envOr("HELMDECK_DB", "helmdeck.db"), "SQLite database path (use ':memory:' for ephemeral)")
	network := flag.String("session-network", envOr("HELMDECK_SESSION_NETWORK", ""), "Docker network to attach session containers to (default: host default)")
	disableRuntime := flag.Bool("disable-runtime", envBool("HELMDECK_DISABLE_RUNTIME"), "skip Docker session runtime (dev mode; /api/v1/sessions returns 503)")
	disableAuth := flag.Bool("disable-auth", envBool("HELMDECK_DISABLE_AUTH"), "skip JWT enforcement on /api/v1/* (DEV ONLY)")
	watchdogIv := flag.Duration("watchdog-interval", 30*time.Second, "session watchdog scan interval")
	mintToken := flag.String("mint-token", "", "mint a JWT for the given subject and exit (uses HELMDECK_JWT_SECRET)")
	mintTokenName := flag.String("mint-token-name", "", "human-readable name for -mint-token output")
	mintTokenClient := flag.String("mint-token-client", "", "client label for -mint-token (claude-code, claude-desktop, openclaw, gemini-cli, ...)")
	mintTokenScopes := flag.String("mint-token-scopes", "admin", "comma-separated scopes for -mint-token")
	mintTokenTTL := flag.Duration("mint-token-ttl", auth.DefaultTTL, "lifetime for -mint-token")
	// -version doubles as the compose.yaml healthcheck command. Exits
	// 0 with "version commit" on stdout so the docker daemon can use
	// the exit code as the health signal without HTTP probing inside
	// the distroless container (no shell, no curl, no wget).
	showVersion := flag.Bool("version", false, "print version and exit (also used by the compose healthcheck)")
	flag.Parse()

	if *showVersion {
		fmt.Println(version, commit)
		return
	}

	logger := slog.New(slog.NewJSONHandler(os.Stdout, &slog.HandlerOptions{Level: slog.LevelInfo}))
	slog.SetDefault(logger)

	// Resolve the JWT issuer first so -mint-token can run without spinning
	// up the rest of the server.
	issuer, autogenerated, err := loadOrGenerateIssuer(logger)
	if err != nil {
		fmt.Fprintln(os.Stderr, "auth init:", err)
		os.Exit(1)
	}

	if *mintToken != "" {
		scopes := parseScopes(*mintTokenScopes)
		tok, err := issuer.Issue(*mintToken, *mintTokenName, *mintTokenClient, scopes, *mintTokenTTL)
		if err != nil {
			fmt.Fprintln(os.Stderr, "mint-token:", err)
			os.Exit(1)
		}
		fmt.Println(tok)
		return
	}

	logger.Info("helmdeck control-plane starting", "version", version, "commit", commit, "addr", *addr, "auth", !*disableAuth, "db", *dbPath)
	if autogenerated {
		logger.Warn("HELMDECK_JWT_SECRET not set; generated an ephemeral secret. Tokens will not survive restart.")
	}

	db, err := store.Open(*dbPath)
	if err != nil {
		fmt.Fprintln(os.Stderr, "store open:", err)
		os.Exit(1)
	}
	defer db.Close()
	auditWriter := audit.NewSQLiteWriter(db)

	// Provider key store. HELMDECK_KEYSTORE_KEY is a 32-byte hex master
	// key; if missing we autogenerate one and warn loudly so operators
	// know rows written this run will be unreadable after a restart.
	ksMaster, ksAutogen, err := loadOrGenerateKeystoreMaster()
	if err != nil {
		fmt.Fprintln(os.Stderr, "keystore init:", err)
		os.Exit(1)
	}
	if ksAutogen {
		logger.Warn("HELMDECK_KEYSTORE_KEY not set; generated an ephemeral master key. Provider keys will be unreadable after restart.")
	}
	ks, err := keystore.New(db, ksMaster)
	if err != nil {
		fmt.Fprintln(os.Stderr, "keystore:", err)
		os.Exit(1)
	}

	// Credential vault (T501). HELMDECK_VAULT_KEY is a separate 32-byte
	// hex master key — intentionally distinct from HELMDECK_KEYSTORE_KEY
	// so a leak of one does not expose the other domain. Same
	// autogenerate-with-warning fallback as the keystore.
	vaultMaster, vaultAutogen, err := loadOrGenerateVaultMaster()
	if err != nil {
		fmt.Fprintln(os.Stderr, "vault init:", err)
		os.Exit(1)
	}
	if vaultAutogen {
		logger.Warn("HELMDECK_VAULT_KEY not set; generated an ephemeral master key. Credentials will be unreadable after restart.")
	}
	vaultStore, err := vault.New(db, vaultMaster)
	if err != nil {
		fmt.Fprintln(os.Stderr, "vault:", err)
		os.Exit(1)
	}

	// Env-hydrate well-known credentials (#142). Operators set
	// HELMDECK_<SVC>_API_KEY in .env.local per the README; this
	// auto-imports each present env var into the vault under its
	// canonical name (elevenlabs-key, etc.) so vault-backed packs
	// (podcast.generate, slides.narrate) work without a separate
	// `POST /vault/credentials` step. User-managed entries are never
	// clobbered — only rows that this routine itself created get
	// re-upserted on subsequent restarts.
	created, updated, skipped := vaultStore.HydrateFromEnv(context.Background(), logger, envOrFile)
	if created+updated+skipped > 0 {
		logger.Info("vault env hydrate done",
			"created", created, "updated", updated, "skipped", skipped)
	}

	// Egress guard (T508). Application-layer SSRF defense — blocks
	// every pack-handler call out to cloud metadata, RFC 1918, and
	// loopback by default. Operators with internal CI hosts that
	// legitimately need to be reachable from session containers
	// allowlist them via HELMDECK_EGRESS_ALLOWLIST (comma-separated
	// CIDRs). The kernel-level companion (iptables on baas-net) is
	// in docs/SECURITY-HARDENING.md.
	egressGuard := security.New(
		security.WithAllowlist(security.AllowlistFromEnv(os.Getenv("HELMDECK_EGRESS_ALLOWLIST"))),
	)

	// Management UI login credentials (T601). The UI's login form
	// posts to /api/v1/auth/login which compares against these in
	// constant time. Empty HELMDECK_ADMIN_PASSWORD disables the
	// login endpoint entirely (returns 503) — operators using only
	// the CLI mint-token path don't need to set it. The default
	// username is "admin"; override via HELMDECK_ADMIN_USERNAME.
	api.AuthAdminPassword = os.Getenv("HELMDECK_ADMIN_PASSWORD")
	if u := os.Getenv("HELMDECK_ADMIN_USERNAME"); u != "" {
		api.AuthAdminUsername = u
	}
	if api.AuthAdminPassword == "" {
		logger.Info("HELMDECK_ADMIN_PASSWORD not set; UI login endpoint will return 503. Mint tokens via the CLI -mint-token flag instead.")
	} else {
		logger.Info("UI login endpoint enabled", "username", api.AuthAdminUsername)
	}

	ctx, stop := signal.NotifyContext(context.Background(), syscall.SIGINT, syscall.SIGTERM)
	defer stop()

	// T510: OpenTelemetry tracing. No-op when neither
	// HELMDECK_OTEL_ENABLED=true nor OTEL_EXPORTER_OTLP_ENDPOINT is
	// set, so the default dev path stays cost-free.
	tp, err := telemetry.Init(ctx, telemetry.Config{
		ServiceName:    "helmdeck-control-plane",
		ServiceVersion: version,
		Insecure:       true,
	})
	if err != nil {
		logger.Warn("telemetry init failed; continuing without tracing", "err", err)
	}
	defer func() {
		if err := tp.Shutdown(context.Background()); err != nil {
			logger.Warn("telemetry shutdown failed", "err", err)
		}
	}()
	if tp.Enabled() {
		logger.Info("OpenTelemetry tracing enabled",
			"endpoint", os.Getenv("OTEL_EXPORTER_OTLP_ENDPOINT"))
	}

	var rt session.Runtime
	if !*disableRuntime {
		opts := []dockerrt.Option{}
		if *network != "" {
			opts = append(opts, dockerrt.WithNetwork(*network))
		}
		// T509 sandbox baseline. Honors HELMDECK_SECCOMP_PROFILE
		// (custom seccomp JSON path; default = docker's built-in
		// curated profile) and HELMDECK_PIDS_LIMIT (max processes
		// per session; default 1024 — see runtime.defaultPidsLimit).
		if profile := os.Getenv("HELMDECK_SECCOMP_PROFILE"); profile != "" {
			opts = append(opts, dockerrt.WithSeccompProfile(profile))
		}
		if raw := os.Getenv("HELMDECK_PIDS_LIMIT"); raw != "" {
			if n, err := strconv.ParseInt(raw, 10, 64); err == nil {
				opts = append(opts, dockerrt.WithPidsLimit(n))
			}
		}
		// HELMDECK_SIDECAR_IMAGE overrides the default sidecar image
		// the runtime spawns when a pack needs a session and no
		// per-spec image is set. Operators building locally with
		// `make sidecar-build` get `helmdeck-sidecar:dev`; the
		// install script sets this env var so the control plane
		// finds it. Falls back to the published ghcr.io image if
		// unset.
		if img := os.Getenv("HELMDECK_SIDECAR_IMAGE"); img != "" {
			opts = append(opts, dockerrt.WithImage(img))
		}
		dr, err := dockerrt.New(opts...)
		if err != nil {
			logger.Warn("docker runtime unavailable; /api/v1/sessions disabled", "err", err)
		} else {
			if err := dr.PruneOrphans(ctx); err != nil {
				logger.Warn("orphan prune failed", "err", err)
			}
			rt = dr
			defer dr.Close()
			wd := session.NewWatchdog(rt, logger, *watchdogIv)
			go wd.Run(ctx)
			logger.Info("session runtime ready", "network", *network, "watchdog_interval", watchdogIv.String())
		}
	} else {
		logger.Info("session runtime disabled by flag")
	}

	// T202a: hydrate the gateway registry from the encrypted keystore
	// at boot AND expose a closure so handler routes can re-hydrate
	// after a key add/rotate/delete (hot reload — no restart needed).
	// LoadCustomOpenAIProviders adds env-var-driven OpenAI-compatible
	// aggregators (today: OpenRouter via HELMDECK_OPENROUTER_API_KEY).
	gwReg := newGatewayRegistryWithRecorder(db)
	rehydrateGateway := func() error {
		if err := gateway.HydrateFromKeystore(ctx, gwReg, keystoreReaderAdapter{ks}, logger); err != nil {
			return err
		}
		gateway.LoadCustomOpenAIProviders(gwReg, logger)
		return nil
	}
	if err := rehydrateGateway(); err != nil {
		logger.Warn("initial gateway hydrate failed; /v1/* will be partial or empty", "err", err)
	}

	// T810 (#28): marketplace catalog service. Reads
	// HELMDECK_MARKETPLACE_URL (default per ADR 034) and exposes
	// /api/v1/marketplace/catalog + /refresh. Setting
	// HELMDECK_MARKETPLACE_DISABLE=1 turns the endpoints off
	// entirely (returns 503) for air-gapped deployments. The
	// startup refresh is async + best-effort — a slow upstream
	// shouldn't block control-plane boot.
	var marketplaceSvc *marketplace.Service
	if os.Getenv("HELMDECK_MARKETPLACE_DISABLE") != "1" {
		mpURL := os.Getenv("HELMDECK_MARKETPLACE_URL")
		if mpURL == "" {
			mpURL = marketplace.DefaultMarketplaceURL
		}
		marketplaceSvc = marketplace.NewService(mpURL, logger.With("subsystem", "marketplace"))
		go func() {
			refreshCtx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
			defer cancel()
			if err := marketplaceSvc.Refresh(refreshCtx); err != nil {
				logger.Warn("initial marketplace refresh failed; catalog will be empty until /refresh succeeds",
					"err", err)
			}
		}()
	}

	deps := api.Deps{
		Logger:           logger,
		Version:          version,
		Runtime:          rt,
		Issuer:           issuer,
		Audit:            auditWriter,
		Gateway:          gwReg,
		RehydrateGateway: rehydrateGateway,
		Keys:             ks,
		MCPRegistry: mcp.NewRegistry(db),
		Vault:       vaultStore,
		Injector:    inject.New(vaultStore, logger.With("subsystem", "inject")),
		Marketplace: marketplaceSvc,
		// T607: expose the SQLite handle so the providers/stats
		// endpoint can run aggregation queries against
		// provider_calls. Other DB-backed endpoints land here
		// over time so we don't have to plumb a fresh accessor
		// per route.
		DB: db,
	}
	packReg := packs.NewPackRegistry()
	deps.PackRegistry = packReg

	// T812 (#30): install/uninstall plumbing. Defaults the install
	// dir to ~/.helmdeck/packs (per ADR 034) but operators can
	// override via HELMDECK_PACKS_DIR. The installer needs both the
	// marketplace service (for catalog lookups) and the pack
	// registry (for hot-load), so it's constructed AFTER packReg.
	if marketplaceSvc != nil {
		installDir := os.Getenv("HELMDECK_PACKS_DIR")
		if installDir == "" {
			if home, err := os.UserHomeDir(); err == nil {
				installDir = filepath.Join(home, ".helmdeck", "packs")
			}
		}
		if installDir != "" {
			if err := os.MkdirAll(installDir, 0o755); err == nil {
				deps.MarketplaceInstaller = marketplace.NewInstaller(
					marketplaceSvc, packReg, installDir,
					logger.With("subsystem", "marketplace.install"))
				logger.Info("marketplace installer ready", "install_dir", installDir)
			} else {
				logger.Warn("marketplace install dir not creatable; install endpoints disabled",
					"install_dir", installDir, "err", err)
			}
		}
	}

	engineOpts := []packs.Option{packs.WithRuntime(rt), packs.WithLogger(logger)}
	var artifactStore packs.ArtifactStore
	if store, err := loadS3StoreFromEnv(ctx); err != nil {
		logger.Warn("S3 artifact store disabled", "err", err)
	} else if store != nil {
		artifactStore = store
		engineOpts = append(engineOpts, packs.WithArtifactStore(store))
		// T302b: plumb the store into Deps so the MCP PackServer can
		// fetch artifact bytes for inline image content in tool results.
		deps.ArtifactStore = store
		logger.Info("S3 artifact store enabled",
			"endpoint", envOrFile("HELMDECK_S3_ENDPOINT", "HELMDECK_S3_ENDPOINT_FILE"),
			"bucket", envOrFile("HELMDECK_S3_BUCKET", "HELMDECK_S3_BUCKET_FILE"))
	}
	if rt != nil {
		cdpFactory := api.DefaultCDPClientFactory(rt)
		deps.CDPFactory = cdpFactory
		// The two CDPFactory interfaces (api + packs) have identical
		// method sets, so an embedding adapter satisfies both without
		// the api package needing to import packs.
		engineOpts = append(engineOpts, packs.WithCDPFactory(cdpFactoryAdapter{cdpFactory}))
		// Backends that implement session.Executor (the docker
		// runtime does after T210) get wired in so packs like
		// slides.render can shell out inside the container, and the
		// desktop REST API (T401) can drive xdotool/scrot.
		if ex, ok := rt.(session.Executor); ok {
			engineOpts = append(engineOpts, packs.WithSessionExecutor(ex))
			deps.Executor = ex
		}
	}
	deps.PackEngine = packs.New(engineOpts...)

	// Artifact TTL janitor (T211b, ADR 031). Only runs when an
	// S3-compatible store is configured — the in-memory store is
	// process-local and gets cleaned up on shutdown anyway.
	if artifactStore != nil {
		janitor := packs.NewJanitor(packs.JanitorConfig{
			Store:      artifactStore,
			Interval:   parseDurationOr("HELMDECK_ARTIFACT_JANITOR_INTERVAL", time.Hour),
			DefaultTTL: parseDurationOr("HELMDECK_ARTIFACT_TTL", 7*24*time.Hour),
			PackTTL: func(name string) (time.Duration, bool) {
				p, err := packReg.Get(name, "")
				if err != nil || p.ArtifactTTL <= 0 {
					return 0, false
				}
				return p.ArtifactTTL, true
			},
			Logger: logger.With("subsystem", "artifact-janitor"),
		})
		go janitor.Run(ctx)
		logger.Info("artifact janitor running",
			"interval", parseDurationOr("HELMDECK_ARTIFACT_JANITOR_INTERVAL", time.Hour),
			"default_ttl", parseDurationOr("HELMDECK_ARTIFACT_TTL", 7*24*time.Hour))
	}

	// Register built-in packs (T208–T210, T402–T403). New packs append here.
	if err := packReg.Register(builtin.ScreenshotURL()); err != nil {
		logger.Warn("register screenshot_url pack failed", "err", err)
	}
	if err := packReg.Register(builtin.BrowserInteract()); err != nil {
		logger.Warn("register browser.interact pack failed", "err", err)
	}
	if err := packReg.Register(builtin.ScrapeSPA()); err != nil {
		logger.Warn("register scrape_spa pack failed", "err", err)
	}
	if err := packReg.Register(builtin.SlidesRender(vaultStore, egressGuard)); err != nil {
		logger.Warn("register slides_render pack failed", "err", err)
	}
	if err := packReg.Register(builtin.DesktopRunAppAndScreenshot()); err != nil {
		logger.Warn("register desktop.run_app_and_screenshot pack failed", "err", err)
	}
	if err := packReg.Register(builtin.DocOCR()); err != nil {
		logger.Warn("register doc.ocr pack failed", "err", err)
	}
	// T807c (ADR 035): doc.parse is Docling-backed. Same pattern as
	// web.scrape — registered unconditionally so agents discovering
	// the catalog see it, handler gates on HELMDECK_DOCLING_ENABLED
	// and returns a typed error pointing operators at the overlay
	// compose file when the toggle is off. doc.ocr stays in the
	// catalog as a lightweight Tesseract-only option for operators
	// who don't need full Docling.
	if err := packReg.Register(builtin.DocParse(egressGuard)); err != nil {
		logger.Warn("register doc.parse pack failed", "err", err)
	}
	if err := packReg.Register(builtin.RepoFetch(vaultStore, egressGuard)); err != nil {
		logger.Warn("register repo.fetch pack failed", "err", err)
	}
	if err := packReg.Register(builtin.RepoMap()); err != nil {
		logger.Warn("register repo.map pack failed", "err", err)
	}
	if err := packReg.Register(builtin.RepoPush(vaultStore, egressGuard)); err != nil {
		logger.Warn("register repo.push pack failed", "err", err)
	}
	if err := packReg.Register(builtin.HTTPFetch(vaultStore, egressGuard)); err != nil {
		logger.Warn("register http.fetch pack failed", "err", err)
	}
	// image.generate (#71) — text → image via fal.ai. Registered
	// unconditionally; the handler hard-fails with a typed
	// missing_credential error if HELMDECK_FAL_KEY isn't set, same
	// shape as podcast.generate / slides.narrate (#138).
	if err := packReg.Register(builtin.ImageGenerate(vaultStore, egressGuard)); err != nil {
		logger.Warn("register image.generate pack failed", "err", err)
	}
	// stock.search (#217): Pexels-backed stock photo search. Same
	// pattern as image.generate — pack-registered unconditionally;
	// the handler hard-fails with a typed missing_credential error
	// when neither HELMDECK_PEXELS_API_KEY nor a `pexels-key` vault
	// entry is configured. Engine-pluggable (Unsplash/Pixabay follow).
	if err := packReg.Register(builtin.StockSearch(vaultStore, egressGuard)); err != nil {
		logger.Warn("register stock.search pack failed", "err", err)
	}
	// T807b (ADR 035): web.scrape is Firecrawl-backed. The pack is
	// registered unconditionally so agents discovering the catalog
	// see it — the handler itself gates on HELMDECK_FIRECRAWL_ENABLED
	// and returns a typed error pointing operators at the overlay
	// compose file if the toggle is off. This is preferable to
	// conditional registration (where the pack silently disappears)
	// because it surfaces the config knob in the error message.
	if err := packReg.Register(builtin.WebScrape(egressGuard)); err != nil {
		logger.Warn("register web.scrape pack failed", "err", err)
	}
	// Phase 5.5 fs/git/cmd pack set — the primitives that turn
	// repo.fetch into a working code-edit loop.
	for _, p := range []*packs.Pack{
		builtin.FSRead(),
		builtin.FSWrite(),
		builtin.FSPatch(),
		builtin.FSList(),
		builtin.FSDelete(),
		builtin.CmdRun(),
		builtin.GitCommit(),
		builtin.GitDiff(),
		builtin.GitLog(),
	} {
		if err := packReg.Register(p); err != nil {
			logger.Warn("register fs/git pack failed", "pack", p.Name, "err", err)
		}
	}
	// Language sidecar packs (Option B per-pack image override).
	// Each pins its own SessionSpec.Image so the runtime spawns the
	// right toolchain container without the rest of the pack catalog
	// having to know about it. New languages plug in here.
	if err := packReg.Register(builtin.PythonRun()); err != nil {
		logger.Warn("register python.run pack failed", "err", err)
	}
	if err := packReg.Register(builtin.NodeRun()); err != nil {
		logger.Warn("register node.run pack failed", "err", err)
	}
	// Core GitHub packs (T617, ADR 034). Use the vault store for PAT
	// resolution — operators add their GitHub token via the Vault panel
	// or `scripts/install.sh`. All four are NeedsSession=false (pure
	// HTTP to api.github.com).
	for _, p := range []*packs.Pack{
		builtin.GitHubCreateIssue(vaultStore),
		builtin.GitHubListIssues(vaultStore),
		builtin.GitHubListPRs(vaultStore),
		builtin.GitHubPostComment(vaultStore),
		builtin.GitHubCreateRelease(vaultStore),
		builtin.GitHubSearch(vaultStore),
	} {
		if err := packReg.Register(p); err != nil {
			logger.Warn("register github pack failed", "pack", p.Name, "err", err)
		}
	}
	// blog.publish (#68): registered unconditionally — body mode works
	// without a gateway dispatcher. The dispatcher is wired in below
	// inside the gateway-conditional block (see vision/research block)
	// when one is configured; we re-register at that point with the
	// dispatcher so prompt mode also works. For deployments without a
	// gateway, prompt mode returns CodeInternal at handler time with
	// a clear "no dispatcher" message.
	if err := packReg.Register(builtin.BlogPublish(vaultStore, egressGuard, nil)); err != nil {
		logger.Warn("register blog.publish pack failed", "err", err)
	}
	// Vision packs (T408) need a gateway dispatcher. Register only when
	// one is configured — operators running in stub mode without
	// providers should still get the rest of the pack catalog.
	if deps.GatewayChain != nil || deps.Gateway != nil {
		var visionDispatcher = pickVisionDispatcher(deps)
		for _, p := range []*packs.Pack{
			builtin.VisionClickAnywhere(visionDispatcher),
			builtin.VisionExtractVisibleText(visionDispatcher),
			builtin.VisionFillFormByLabel(visionDispatcher),
			// T807e (ADR 035): web.test is the natural-language
			// front door for browser automation — drives the
			// sidecar-bundled Playwright MCP child (T807a) through
			// an LLM-planned tool-call loop. Same gateway dispatcher
			// as the vision packs; requires a session whose
			// PlaywrightMCPEndpoint is populated, so it piggybacks
			// on the same conditional registration path.
			builtin.WebTest(visionDispatcher, egressGuard),
			// T622 (ADR 035): research.deep — Firecrawl search +
			// per-source scrape + LLM synthesis in a single pack
			// call. Needs the gateway dispatcher for synthesis, so
			// it rides the same conditional registration as the
			// vision and web.test packs. The Firecrawl side is
			// gated separately at handler-time on
			// HELMDECK_FIRECRAWL_ENABLED, matching web.scrape.
			builtin.ResearchDeep(visionDispatcher),
			// T623 (ADR 035): content.ground — LLM-assisted claim
			// extraction + Firecrawl source grounding + in-place
			// fs rewrite. Session-scoped (reads/writes a file
			// inside a session-local clone) and LLM-backed, so
			// like research.deep it rides this conditional block.
			builtin.ContentGround(visionDispatcher),
			// T406 (revived): slides.narrate — Marp slides → narrated
			// MP4 video via ElevenLabs TTS + ffmpeg + YouTube metadata
			// via gateway LLM. Vault-stored ElevenLabs API key; degrades
			// to silent video when key is missing.
			builtin.SlidesNarrate(visionDispatcher, vaultStore, egressGuard),
		} {
			if err := packReg.Register(p); err != nil {
				logger.Warn("register vision pack failed", "pack", p.Name, "err", err)
			}
		}
		// blog.publish prompt mode: re-register with the dispatcher so
		// the prompt+model body path works. The body-mode-only
		// registration above is overwritten by the registry's last-wins
		// semantics. Body mode keeps working either way.
		if err := packReg.Register(builtin.BlogPublish(vaultStore, egressGuard, visionDispatcher)); err != nil {
			logger.Warn("register blog.publish (with dispatcher) failed", "err", err)
		}
		// podcast.generate prompt + source_url/source_text modes need
		// the dispatcher for LLM script generation. Script mode (mode A)
		// works without the dispatcher; the body-mode-only registration
		// is below the conditional. Last-wins semantics — same pattern
		// as blog.publish.
		if err := packReg.Register(builtin.PodcastGenerate(vaultStore, egressGuard, visionDispatcher)); err != nil {
			logger.Warn("register podcast.generate (with dispatcher) failed", "err", err)
		}
	}
	// podcast.generate body-mode-only registration: ensures script
	// mode works in deployments without a gateway. The conditional
	// re-registration above overrides this when the dispatcher is
	// configured.
	if err := packReg.Register(builtin.PodcastGenerate(vaultStore, egressGuard, nil)); err != nil {
		logger.Warn("register podcast.generate pack failed", "err", err)
	}

	// hyperframes.render (#200): HTML/CSS/JS composition → MP4 via
	// the helmdeck-sidecar-hyperframes image. No dispatcher / vault /
	// egress dependency — the render runs entirely inside the sidecar
	// and the composition supplies its own assets (or embeds a
	// presigned podcast.generate audio URL for chained workflows).
	if err := packReg.Register(builtin.HyperframesRender()); err != nil {
		logger.Warn("register hyperframes.render pack failed", "err", err)
	}

	// Operator-supplied command packs (T811 MVP). Drop executables
	// into $HELMDECK_COMMAND_PACKS_DIR and the control plane
	// registers each as `cmd.<basename>`. Schemas are passthrough
	// today; a manifest format with typed schemas ships in v0.13.0.
	if dir := os.Getenv("HELMDECK_COMMAND_PACKS_DIR"); dir != "" {
		for _, p := range builtin.LoadCommandPacks(ctx, logger, dir) {
			if err := packReg.Register(p); err != nil {
				logger.Warn("register command pack failed", "name", p.Name, "err", err)
			}
		}
	}

	if *disableAuth {
		deps.Issuer = nil
		logger.Warn("auth disabled by flag; /api/v1/* is unprotected (DEV ONLY)")
	}
	srv := &http.Server{
		Addr:              *addr,
		Handler:           api.NewRouter(deps),
		ReadHeaderTimeout: 5 * time.Second,
	}

	go func() {
		if err := srv.ListenAndServe(); err != nil && !errors.Is(err, http.ErrServerClosed) {
			logger.Error("server failed", "err", err)
			stop()
		}
	}()

	<-ctx.Done()
	logger.Info("shutdown signal received")

	shutdownCtx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	if err := srv.Shutdown(shutdownCtx); err != nil {
		logger.Error("graceful shutdown failed", "err", err)
		os.Exit(1)
	}
	logger.Info("control-plane stopped cleanly")
}

func envOr(key, fallback string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return fallback
}

func envBool(key string) bool {
	v := os.Getenv(key)
	return v == "1" || v == "true" || v == "yes"
}

// loadOrGenerateIssuer reads HELMDECK_JWT_SECRET (hex or raw ≥32 chars) and
// constructs an Issuer. If the env var is missing, it autogenerates an
// ephemeral secret and reports autogenerated=true so main can warn loudly.
func loadOrGenerateIssuer(logger *slog.Logger) (*auth.Issuer, bool, error) {
	if raw := os.Getenv("HELMDECK_JWT_SECRET"); raw != "" {
		iss, err := auth.NewIssuer([]byte(raw))
		if err != nil {
			return nil, false, err
		}
		return iss, false, nil
	}
	gen, err := auth.GenerateSecret()
	if err != nil {
		return nil, false, err
	}
	iss, err := auth.NewIssuer([]byte(gen))
	if err != nil {
		return nil, false, err
	}
	return iss, true, nil
}

// loadOrGenerateVaultMaster mirrors loadOrGenerateKeystoreMaster
// but reads HELMDECK_VAULT_KEY. The two keys are intentionally
// separate (ADR 007) so a leak of one does not expose the other.
func loadOrGenerateVaultMaster() ([]byte, bool, error) {
	if raw := os.Getenv("HELMDECK_VAULT_KEY"); raw != "" {
		b, err := vault.ParseMasterKey(raw)
		return b, false, err
	}
	hex, err := vault.GenerateMasterKey()
	if err != nil {
		return nil, false, err
	}
	b, err := vault.ParseMasterKey(hex)
	return b, true, err
}

// pickVisionDispatcher mirrors the precedence used by api/vision.go:
// the gateway chain when present (it includes fallback rules), otherwise
// the bare registry. Returns nil only when neither is configured, in
// which case the caller skips vision pack registration entirely.
func pickVisionDispatcher(deps api.Deps) vision.Dispatcher {
	if deps.GatewayChain != nil {
		return deps.GatewayChain
	}
	if deps.Gateway != nil {
		return deps.Gateway
	}
	return nil
}

// parseDurationOr reads a Go duration string from envKey and returns
// it. Falls back to def when the env var is unset, empty, or invalid;
// invalid values are silently ignored because the janitor is best-
// effort infrastructure that should never refuse to start over a typo.
func parseDurationOr(envKey string, def time.Duration) time.Duration {
	v := os.Getenv(envKey)
	if v == "" {
		return def
	}
	d, err := time.ParseDuration(v)
	if err != nil || d <= 0 {
		return def
	}
	return d
}

// envOrFile returns the value of envKey if set; otherwise reads the
// path in fileKey, trims surrounding whitespace, and returns the
// contents. The two-variant pattern matches docker-secrets and lets
// the bundled Garage init service (T211a) hand credentials to the
// control plane via a shared volume without baking them into the
// compose env, while still letting operators with an external S3
// configure everything via plain env vars.
func envOrFile(envKey, fileKey string) string {
	if v := os.Getenv(envKey); v != "" {
		return v
	}
	path := os.Getenv(fileKey)
	if path == "" {
		return ""
	}
	b, err := os.ReadFile(path)
	if err != nil {
		return ""
	}
	return strings.TrimSpace(string(b))
}

// keystoreReaderAdapter wraps *keystore.Store so it satisfies
// gateway.KeystoreReader. The interface lives in internal/gateway/
// (not internal/keystore/) so the gateway package doesn't have to
// import database/sql. The adapter converts []keystore.Record into
// []gateway.KeystoreRecord and forwards Decrypt 1:1.
type keystoreReaderAdapter struct {
	ks *keystore.Store
}

func (a keystoreReaderAdapter) List(ctx context.Context, provider string) ([]gateway.KeystoreRecord, error) {
	recs, err := a.ks.List(ctx, provider)
	if err != nil {
		return nil, err
	}
	out := make([]gateway.KeystoreRecord, 0, len(recs))
	for _, r := range recs {
		out = append(out, gateway.KeystoreRecord{
			ID:        r.ID,
			Provider:  r.Provider,
			Label:     r.Label,
			CreatedAt: r.CreatedAt,
		})
	}
	return out, nil
}

func (a keystoreReaderAdapter) Decrypt(ctx context.Context, id string) (string, error) {
	return a.ks.Decrypt(ctx, id)
}

// newGatewayRegistryWithRecorder constructs a fresh gateway.Registry
// wired to a SQLite-backed CallRecorder so every dispatch lands in
// provider_calls (T607). When db is nil (tests / dev mode without a
// database) the registry uses NoopRecorder and the metrics path is
// silently disabled.
func newGatewayRegistryWithRecorder(db *sql.DB) *gateway.Registry {
	reg := gateway.NewRegistry()
	if db != nil {
		reg.Recorder = gateway.NewSQLiteRecorder(db)
	}
	return reg
}

// loadS3StoreFromEnv builds an S3 artifact store from HELMDECK_S3_*
// env vars (and the matching *_FILE variants). Returns (nil, nil)
// when S3 is not configured (operators who want the in-memory store
// leave both forms unset). Any error is logged at startup but does
// not abort the process — falling back to in-memory is preferable to
// refusing to boot.
func loadS3StoreFromEnv(ctx context.Context) (*packs.S3ArtifactStore, error) {
	endpoint := envOrFile("HELMDECK_S3_ENDPOINT", "HELMDECK_S3_ENDPOINT_FILE")
	if endpoint == "" {
		return nil, nil
	}
	// minio-go's New() rejects fully-qualified URLs ("Endpoint url
	// cannot have fully qualified paths") and wants bare host:port.
	// The garage-init credential file writes the natural form
	// http://garage:3900, and operators pasting an endpoint into
	// HELMDECK_S3_ENDPOINT will reach for the same shape. Strip the
	// scheme here and derive UseSSL from it so both spellings work.
	useSSL := os.Getenv("HELMDECK_S3_USE_SSL") == "true"
	if u, err := url.Parse(endpoint); err == nil && u.Scheme != "" && u.Host != "" {
		endpoint = u.Host
		switch u.Scheme {
		case "https":
			useSSL = true
		case "http":
			useSSL = false
		}
	}
	cfg := packs.S3Config{
		Endpoint:        endpoint,
		Bucket:          envOrFile("HELMDECK_S3_BUCKET", "HELMDECK_S3_BUCKET_FILE"),
		AccessKeyID:     envOrFile("HELMDECK_S3_ACCESS_KEY", "HELMDECK_S3_ACCESS_KEY_FILE"),
		SecretAccessKey: envOrFile("HELMDECK_S3_SECRET_KEY", "HELMDECK_S3_SECRET_KEY_FILE"),
		Region:          os.Getenv("HELMDECK_S3_REGION"),
		UseSSL:          useSSL,
		PublicEndpoint:  envOrFile("HELMDECK_S3_PUBLIC_ENDPOINT", "HELMDECK_S3_PUBLIC_ENDPOINT_FILE"),
	}
	return packs.NewS3ArtifactStore(ctx, cfg)
}

// cdpFactoryAdapter bridges api.CDPClientFactory to packs.CDPFactory.
// Both interfaces have the same method set; the embedded interface
// promotes Get and Evict, so the struct satisfies packs.CDPFactory
// without packs needing to import api.
type cdpFactoryAdapter struct {
	api.CDPClientFactory
}

func loadOrGenerateKeystoreMaster() ([]byte, bool, error) {
	if raw := os.Getenv("HELMDECK_KEYSTORE_KEY"); raw != "" {
		b, err := keystore.ParseMasterKey(raw)
		return b, false, err
	}
	hex, err := keystore.GenerateMasterKey()
	if err != nil {
		return nil, false, err
	}
	b, err := keystore.ParseMasterKey(hex)
	return b, true, err
}

func parseScopes(csv string) []auth.Scope {
	parts := strings.Split(csv, ",")
	out := make([]auth.Scope, 0, len(parts))
	for _, p := range parts {
		p = strings.TrimSpace(p)
		if p == "" {
			continue
		}
		out = append(out, auth.Scope(p))
	}
	return out
}
