// Command control-plane is the helmdeck Golang control plane.
//
// It serves the REST API, the embedded React UI, the AI gateway, the MCP
// registry, the credential vault, and orchestrates ephemeral browser session
// containers via the SessionRuntime interface (see ADR 002, 009).
package main

import (
	"context"
	"errors"
	"flag"
	"fmt"
	"log/slog"
	"net/http"
	"os"
	"os/signal"
	"strings"
	"syscall"
	"time"

	"github.com/tosin2013/helmdeck/internal/api"
	"github.com/tosin2013/helmdeck/internal/audit"
	"github.com/tosin2013/helmdeck/internal/auth"
	"github.com/tosin2013/helmdeck/internal/gateway"
	"github.com/tosin2013/helmdeck/internal/keystore"
	"github.com/tosin2013/helmdeck/internal/mcp"
	"github.com/tosin2013/helmdeck/internal/packs"
	"github.com/tosin2013/helmdeck/internal/packs/builtin"
	"github.com/tosin2013/helmdeck/internal/session"
	dockerrt "github.com/tosin2013/helmdeck/internal/session/docker"
	"github.com/tosin2013/helmdeck/internal/store"
)

var (
	version = "dev"     // overridden at build time via -ldflags
	commit  = "unknown" // overridden at build time via -ldflags
)

func main() {
	addr := flag.String("addr", envOr("HELMDECK_ADDR", ":3000"), "listen address")
	dbPath := flag.String("db", envOr("HELMDECK_DB", "helmdeck.db"), "SQLite database path (use ':memory:' for ephemeral)")
	network := flag.String("session-network", envOr("HELMDECK_SESSION_NETWORK", ""), "Docker network to attach session containers to (default: host default)")
	disableRuntime := flag.Bool("disable-runtime", envBool("HELMDECK_DISABLE_RUNTIME"), "skip Docker session runtime (dev mode; /api/v1/sessions returns 503)")
	disableAuth := flag.Bool("disable-auth", envBool("HELMDECK_DISABLE_AUTH"), "skip JWT enforcement on /api/v1/* (DEV ONLY)")
	watchdogIv := flag.Duration("watchdog-interval", 30*time.Second, "session watchdog scan interval")
	mintToken := flag.String("mint-token", "", "mint a JWT for the given subject and exit (uses HELMDECK_JWT_SECRET)")
	mintTokenName := flag.String("mint-token-name", "", "human-readable name for -mint-token output")
	mintTokenClient := flag.String("mint-token-client", "", "client label for -mint-token (claude-code, claude-desktop, openclaw, gemini-cli, ...)")
	mintTokenScopes := flag.String("mint-token-scopes", "admin", "comma-separated scopes for -mint-token")
	mintTokenTTL := flag.Duration("mint-token-ttl", auth.DefaultTTL, "lifetime for -mint-token")
	flag.Parse()

	logger := slog.New(slog.NewJSONHandler(os.Stdout, &slog.HandlerOptions{Level: slog.LevelInfo}))
	slog.SetDefault(logger)

	// Resolve the JWT issuer first so -mint-token can run without spinning
	// up the rest of the server.
	issuer, autogenerated, err := loadOrGenerateIssuer(logger)
	if err != nil {
		fmt.Fprintln(os.Stderr, "auth init:", err)
		os.Exit(1)
	}

	if *mintToken != "" {
		scopes := parseScopes(*mintTokenScopes)
		tok, err := issuer.Issue(*mintToken, *mintTokenName, *mintTokenClient, scopes, *mintTokenTTL)
		if err != nil {
			fmt.Fprintln(os.Stderr, "mint-token:", err)
			os.Exit(1)
		}
		fmt.Println(tok)
		return
	}

	logger.Info("helmdeck control-plane starting", "version", version, "commit", commit, "addr", *addr, "auth", !*disableAuth, "db", *dbPath)
	if autogenerated {
		logger.Warn("HELMDECK_JWT_SECRET not set; generated an ephemeral secret. Tokens will not survive restart.")
	}

	db, err := store.Open(*dbPath)
	if err != nil {
		fmt.Fprintln(os.Stderr, "store open:", err)
		os.Exit(1)
	}
	defer db.Close()
	auditWriter := audit.NewSQLiteWriter(db)

	// Provider key store. HELMDECK_KEYSTORE_KEY is a 32-byte hex master
	// key; if missing we autogenerate one and warn loudly so operators
	// know rows written this run will be unreadable after a restart.
	ksMaster, ksAutogen, err := loadOrGenerateKeystoreMaster()
	if err != nil {
		fmt.Fprintln(os.Stderr, "keystore init:", err)
		os.Exit(1)
	}
	if ksAutogen {
		logger.Warn("HELMDECK_KEYSTORE_KEY not set; generated an ephemeral master key. Provider keys will be unreadable after restart.")
	}
	ks, err := keystore.New(db, ksMaster)
	if err != nil {
		fmt.Fprintln(os.Stderr, "keystore:", err)
		os.Exit(1)
	}

	ctx, stop := signal.NotifyContext(context.Background(), syscall.SIGINT, syscall.SIGTERM)
	defer stop()

	var rt session.Runtime
	if !*disableRuntime {
		opts := []dockerrt.Option{}
		if *network != "" {
			opts = append(opts, dockerrt.WithNetwork(*network))
		}
		dr, err := dockerrt.New(opts...)
		if err != nil {
			logger.Warn("docker runtime unavailable; /api/v1/sessions disabled", "err", err)
		} else {
			if err := dr.PruneOrphans(ctx); err != nil {
				logger.Warn("orphan prune failed", "err", err)
			}
			rt = dr
			defer dr.Close()
			wd := session.NewWatchdog(rt, logger, *watchdogIv)
			go wd.Run(ctx)
			logger.Info("session runtime ready", "network", *network, "watchdog_interval", watchdogIv.String())
		}
	} else {
		logger.Info("session runtime disabled by flag")
	}

	deps := api.Deps{
		Logger:  logger,
		Version: version,
		Runtime: rt,
		Issuer:  issuer,
		Audit:   auditWriter,
		// Empty registry today; T202 wires real provider adapters into it
		// at startup. The routes still mount so misconfiguration shows up
		// as an empty /v1/models response rather than a 503.
		Gateway:     gateway.NewRegistry(),
		Keys:        ks,
		MCPRegistry: mcp.NewRegistry(db),
	}
	packReg := packs.NewPackRegistry()
	deps.PackRegistry = packReg

	engineOpts := []packs.Option{packs.WithRuntime(rt), packs.WithLogger(logger)}
	var artifactStore packs.ArtifactStore
	if store, err := loadS3StoreFromEnv(ctx); err != nil {
		logger.Warn("S3 artifact store disabled", "err", err)
	} else if store != nil {
		artifactStore = store
		engineOpts = append(engineOpts, packs.WithArtifactStore(store))
		logger.Info("S3 artifact store enabled", "endpoint", os.Getenv("HELMDECK_S3_ENDPOINT"), "bucket", os.Getenv("HELMDECK_S3_BUCKET"))
	}
	if rt != nil {
		cdpFactory := api.DefaultCDPClientFactory(rt)
		deps.CDPFactory = cdpFactory
		// The two CDPFactory interfaces (api + packs) have identical
		// method sets, so an embedding adapter satisfies both without
		// the api package needing to import packs.
		engineOpts = append(engineOpts, packs.WithCDPFactory(cdpFactoryAdapter{cdpFactory}))
		// Backends that implement session.Executor (the docker
		// runtime does after T210) get wired in so packs like
		// slides.render can shell out inside the container.
		if ex, ok := rt.(session.Executor); ok {
			engineOpts = append(engineOpts, packs.WithSessionExecutor(ex))
		}
	}
	deps.PackEngine = packs.New(engineOpts...)

	// Artifact TTL janitor (T211b, ADR 031). Only runs when an
	// S3-compatible store is configured — the in-memory store is
	// process-local and gets cleaned up on shutdown anyway.
	if artifactStore != nil {
		janitor := packs.NewJanitor(packs.JanitorConfig{
			Store:      artifactStore,
			Interval:   parseDurationOr("HELMDECK_ARTIFACT_JANITOR_INTERVAL", time.Hour),
			DefaultTTL: parseDurationOr("HELMDECK_ARTIFACT_TTL", 7*24*time.Hour),
			PackTTL: func(name string) (time.Duration, bool) {
				p, err := packReg.Get(name, "")
				if err != nil || p.ArtifactTTL <= 0 {
					return 0, false
				}
				return p.ArtifactTTL, true
			},
			Logger: logger.With("subsystem", "artifact-janitor"),
		})
		go janitor.Run(ctx)
		logger.Info("artifact janitor running",
			"interval", parseDurationOr("HELMDECK_ARTIFACT_JANITOR_INTERVAL", time.Hour),
			"default_ttl", parseDurationOr("HELMDECK_ARTIFACT_TTL", 7*24*time.Hour))
	}

	// Register built-in packs (T208–T210). T209/T210 packs append here
	// as they land.
	if err := packReg.Register(builtin.ScreenshotURL()); err != nil {
		logger.Warn("register screenshot_url pack failed", "err", err)
	}
	if err := packReg.Register(builtin.ScrapeSPA()); err != nil {
		logger.Warn("register scrape_spa pack failed", "err", err)
	}
	if err := packReg.Register(builtin.SlidesRender()); err != nil {
		logger.Warn("register slides_render pack failed", "err", err)
	}
	if *disableAuth {
		deps.Issuer = nil
		logger.Warn("auth disabled by flag; /api/v1/* is unprotected (DEV ONLY)")
	}
	srv := &http.Server{
		Addr:              *addr,
		Handler:           api.NewRouter(deps),
		ReadHeaderTimeout: 5 * time.Second,
	}

	go func() {
		if err := srv.ListenAndServe(); err != nil && !errors.Is(err, http.ErrServerClosed) {
			logger.Error("server failed", "err", err)
			stop()
		}
	}()

	<-ctx.Done()
	logger.Info("shutdown signal received")

	shutdownCtx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	if err := srv.Shutdown(shutdownCtx); err != nil {
		logger.Error("graceful shutdown failed", "err", err)
		os.Exit(1)
	}
	logger.Info("control-plane stopped cleanly")
}

func envOr(key, fallback string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return fallback
}

func envBool(key string) bool {
	v := os.Getenv(key)
	return v == "1" || v == "true" || v == "yes"
}

// loadOrGenerateIssuer reads HELMDECK_JWT_SECRET (hex or raw ≥32 chars) and
// constructs an Issuer. If the env var is missing, it autogenerates an
// ephemeral secret and reports autogenerated=true so main can warn loudly.
func loadOrGenerateIssuer(logger *slog.Logger) (*auth.Issuer, bool, error) {
	if raw := os.Getenv("HELMDECK_JWT_SECRET"); raw != "" {
		iss, err := auth.NewIssuer([]byte(raw))
		if err != nil {
			return nil, false, err
		}
		return iss, false, nil
	}
	gen, err := auth.GenerateSecret()
	if err != nil {
		return nil, false, err
	}
	iss, err := auth.NewIssuer([]byte(gen))
	if err != nil {
		return nil, false, err
	}
	return iss, true, nil
}

// parseDurationOr reads a Go duration string from envKey and returns
// it. Falls back to def when the env var is unset, empty, or invalid;
// invalid values are silently ignored because the janitor is best-
// effort infrastructure that should never refuse to start over a typo.
func parseDurationOr(envKey string, def time.Duration) time.Duration {
	v := os.Getenv(envKey)
	if v == "" {
		return def
	}
	d, err := time.ParseDuration(v)
	if err != nil || d <= 0 {
		return def
	}
	return d
}

// envOrFile returns the value of envKey if set; otherwise reads the
// path in fileKey, trims surrounding whitespace, and returns the
// contents. The two-variant pattern matches docker-secrets and lets
// the bundled Garage init service (T211a) hand credentials to the
// control plane via a shared volume without baking them into the
// compose env, while still letting operators with an external S3
// configure everything via plain env vars.
func envOrFile(envKey, fileKey string) string {
	if v := os.Getenv(envKey); v != "" {
		return v
	}
	path := os.Getenv(fileKey)
	if path == "" {
		return ""
	}
	b, err := os.ReadFile(path)
	if err != nil {
		return ""
	}
	return strings.TrimSpace(string(b))
}

// loadS3StoreFromEnv builds an S3 artifact store from HELMDECK_S3_*
// env vars (and the matching *_FILE variants). Returns (nil, nil)
// when S3 is not configured (operators who want the in-memory store
// leave both forms unset). Any error is logged at startup but does
// not abort the process — falling back to in-memory is preferable to
// refusing to boot.
func loadS3StoreFromEnv(ctx context.Context) (*packs.S3ArtifactStore, error) {
	endpoint := envOrFile("HELMDECK_S3_ENDPOINT", "HELMDECK_S3_ENDPOINT_FILE")
	if endpoint == "" {
		return nil, nil
	}
	cfg := packs.S3Config{
		Endpoint:        endpoint,
		Bucket:          envOrFile("HELMDECK_S3_BUCKET", "HELMDECK_S3_BUCKET_FILE"),
		AccessKeyID:     envOrFile("HELMDECK_S3_ACCESS_KEY", "HELMDECK_S3_ACCESS_KEY_FILE"),
		SecretAccessKey: envOrFile("HELMDECK_S3_SECRET_KEY", "HELMDECK_S3_SECRET_KEY_FILE"),
		Region:          os.Getenv("HELMDECK_S3_REGION"),
		UseSSL:          os.Getenv("HELMDECK_S3_USE_SSL") == "true",
		PublicEndpoint:  envOrFile("HELMDECK_S3_PUBLIC_ENDPOINT", "HELMDECK_S3_PUBLIC_ENDPOINT_FILE"),
	}
	return packs.NewS3ArtifactStore(ctx, cfg)
}

// cdpFactoryAdapter bridges api.CDPClientFactory to packs.CDPFactory.
// Both interfaces have the same method set; the embedded interface
// promotes Get and Evict, so the struct satisfies packs.CDPFactory
// without packs needing to import api.
type cdpFactoryAdapter struct {
	api.CDPClientFactory
}

func loadOrGenerateKeystoreMaster() ([]byte, bool, error) {
	if raw := os.Getenv("HELMDECK_KEYSTORE_KEY"); raw != "" {
		b, err := keystore.ParseMasterKey(raw)
		return b, false, err
	}
	hex, err := keystore.GenerateMasterKey()
	if err != nil {
		return nil, false, err
	}
	b, err := keystore.ParseMasterKey(hex)
	return b, true, err
}

func parseScopes(csv string) []auth.Scope {
	parts := strings.Split(csv, ",")
	out := make([]auth.Scope, 0, len(parts))
	for _, p := range parts {
		p = strings.TrimSpace(p)
		if p == "" {
			continue
		}
		out = append(out, auth.Scope(p))
	}
	return out
}
