#!/usr/bin/env bash
# Four-client MCP bridge smoke matrix (T308).
#
# Boots the same Compose stack make smoke uses, then for each
# supported client (claude-code, claude-desktop, openclaw, gemini-cli):
#
#   1. Fetches the connect snippet from /api/v1/connect/{client} and
#      asserts the JSON parses with the expected shape.
#   2. Spawns the freshly-built helmdeck-mcp binary with HELMDECK_URL
#      and HELMDECK_TOKEN — the same env every supported client sets.
#   3. Pipes a JSON-RPC initialize -> tools/list -> tools/call sequence
#      for browser.screenshot_url through stdio and asserts the
#      resulting base64 payload starts with the PNG magic bytes.
#
# Per ADR 025, the wire contract every client uses is identical at the
# stdio MCP layer; the only per-client variation is the config file
# shape, which the snippet generator (T309) covers and which step (1)
# verifies here. That makes one bridge invocation per client both
# necessary and sufficient for the exit-gate assertion.
#
# Exits 0 on success, non-zero on the first failed leg.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
COMPOSE_FILE="${REPO_ROOT}/deploy/compose/compose.yaml"
ENV_FILE="${REPO_ROOT}/deploy/compose/.env.clients-smoke"
RUNTIME_ENV_FILE="${REPO_ROOT}/deploy/compose/.env.local"
SIDECAR_IMAGE="${SIDECAR_IMAGE:-helmdeck-sidecar:dev}"
PORT="${PORT:-3000}"
BRIDGE_BIN="${BRIDGE_BIN:-${REPO_ROOT}/bin/helmdeck-mcp}"

# Track whether THIS script created .env.local. If yes, clean it up at
# exit. If a real one was already there (operator running locally), do
# NOT touch it — clobbering an operator's vault/keystore keys is the
# kind of mistake that's easy to make and hard to recover from.
CREATED_RUNTIME_ENV=0

CLIENTS=(claude-code claude-desktop openclaw gemini-cli)

cleanup() {
  local rc=$?
  if [[ $rc -ne 0 ]]; then
    echo "--- clients-smoke FAILED, dumping control-plane logs ---" >&2
    docker compose -f "${COMPOSE_FILE}" --env-file "${ENV_FILE}" logs control-plane 2>&1 | tail -80 >&2 || true
  fi
  docker compose -f "${COMPOSE_FILE}" --env-file "${ENV_FILE}" down -v --remove-orphans >/dev/null 2>&1 || true
  rm -f "${ENV_FILE}"
  if [[ "${CREATED_RUNTIME_ENV}" == "1" ]]; then
    rm -f "${RUNTIME_ENV_FILE}"
  fi
  exit $rc
}
trap cleanup EXIT

require() { command -v "$1" >/dev/null 2>&1 || { echo "clients-smoke: missing tool: $1" >&2; exit 2; }; }
require docker
require curl
require jq

if [[ ! -x "${BRIDGE_BIN}" ]]; then
  echo "clients-smoke: building helmdeck-mcp at ${BRIDGE_BIN}"
  mkdir -p "$(dirname "${BRIDGE_BIN}")"
  (cd "${REPO_ROOT}" && go build -o "${BRIDGE_BIN}" ./cmd/helmdeck-mcp)
fi

# Reuse the same env shape make smoke writes so the compose stack
# comes up identically.
SECRET="$(openssl rand -hex 32)"
# Docker socket GID for compose's group_add substitution. On Ubuntu
# 24.04 (current GitHub Actions runners) docker.sock is owned by GID
# 127; older 20.04-era runners used 999; the compose default fallback
# is 999 which won't work on modern runners. Stat the socket to get
# the right value at runtime.
DOCKER_GID="$(stat -c '%g' /var/run/docker.sock 2>/dev/null || echo 999)"
cat > "${ENV_FILE}" <<EOF
HELMDECK_JWT_SECRET=${SECRET}
HELMDECK_PORT=${PORT}
SIDECAR_IMAGE=${SIDECAR_IMAGE}
HELMDECK_DOCKER_GID=${DOCKER_GID}
EOF

# compose.yaml's control-plane service has env_file: .env.local for
# runtime container vars (HELMDECK_VAULT_KEY, HELMDECK_KEYSTORE_KEY,
# HELMDECK_ADMIN_PASSWORD). On a fresh CI runner this file doesn't
# exist; on an operator's machine it usually does. Bootstrap one with
# throwaway secrets only when missing — never overwrite an existing
# operator-managed file.
if [[ ! -f "${RUNTIME_ENV_FILE}" ]]; then
  echo "--- bootstrapping throwaway ${RUNTIME_ENV_FILE##*/} for the compose run ---"
  ADMIN_PASSWORD="$(openssl rand -base64 24 | tr -d '/+=' | head -c 32)"
  umask 077
  cat > "${RUNTIME_ENV_FILE}" <<EOF
# AUTO-GENERATED by scripts/clients-smoke.sh — throwaway secrets for a
# single CI run. Cleaned up at script exit.
HELMDECK_JWT_SECRET=${SECRET}
HELMDECK_VAULT_KEY=$(openssl rand -hex 32)
HELMDECK_KEYSTORE_KEY=$(openssl rand -hex 32)
HELMDECK_ADMIN_PASSWORD=${ADMIN_PASSWORD}
EOF
  CREATED_RUNTIME_ENV=1
fi

echo "--- booting compose stack ---"
docker compose -f "${COMPOSE_FILE}" --env-file "${ENV_FILE}" up -d --wait

URL="http://localhost:${PORT}"
# Mint a JWT via the control-plane binary's -mint-token flag, exec'd
# inside the running container so it uses the same HELMDECK_JWT_SECRET
# the server was started with. The previous "go run scripts/mint-token"
# path referenced a script that doesn't exist; the curl fallback hit
# /api/v1/dev/token which also doesn't exist (would 401 from auth).
TOKEN="$(docker exec helmdeck-control-plane /usr/local/bin/control-plane \
  -mint-token clients-smoke -mint-token-scopes admin 2>/dev/null | tail -1)"
if [[ -z "${TOKEN}" ]]; then
  echo "clients-smoke: could not mint a JWT via docker exec" >&2
  exit 1
fi

call_bridge() {
  # Stream three JSON-RPC frames into helmdeck-mcp on stdin and read
  # responses from stdout. The bridge proxies them verbatim to the
  # platform's WebSocket MCP endpoint. We rely on line-delimited JSON
  # in both directions (the bridge wire format).
  #
  # We keep stdin open for an extra ~30s after the last frame because
  # the bridge closes the WebSocket when stdin EOFs — and tools/call
  # for browser.screenshot_url takes ~5s server-side (sidecar spawn +
  # navigation + screenshot). EOF'ing immediately races the response
  # back to us; the in-flight request gets aborted server-side and we
  # see zero responses on stdout. The outer `timeout 60` caps total
  # wall time so a hung server doesn't stall CI.
  local payload
  payload="$(jq -nc \
    '{jsonrpc:"2.0",id:1,method:"initialize",params:{protocolVersion:"2024-11-05",capabilities:{},clientInfo:{name:"clients-smoke",version:"0.0.0"}}},
     {jsonrpc:"2.0",id:2,method:"tools/list"},
     {jsonrpc:"2.0",id:3,method:"tools/call",params:{name:"browser.screenshot_url",arguments:{url:"https://example.com"}}}')"
  HELMDECK_URL="${URL}" HELMDECK_TOKEN="${TOKEN}" \
    timeout 60 bash -c '{ printf "%s\n" "$1"; sleep 30; } | "$2"' _ "${payload}" "${BRIDGE_BIN}"
}

for client in "${CLIENTS[@]}"; do
  echo "--- ${client}: fetching connect snippet ---"
  snippet="$(curl -fsS -H "Authorization: Bearer ${TOKEN}" "${URL}/api/v1/connect/${client}")"
  echo "${snippet}" | jq -e '.client and .install_path and .config' >/dev/null \
    || { echo "clients-smoke: ${client} snippet malformed" >&2; exit 1; }

  echo "--- ${client}: invoking browser.screenshot_url via bridge ---"
  out="$(call_bridge)"
  # Find the tools/call response (id=3) and pull out the first base64
  # image content block, then check the magic bytes.
  png_b64="$(echo "${out}" | jq -rs '
    map(select(.id == 3)) | .[0].result.content
    | map(select(.type == "image")) | .[0].data // empty
  ')"
  if [[ -z "${png_b64}" ]]; then
    echo "clients-smoke: ${client} got no image content" >&2
    echo "${out}" >&2
    exit 1
  fi
  magic="$(echo "${png_b64}" | base64 -d 2>/dev/null | head -c 8 | xxd -p || true)"
  if [[ "${magic}" != "89504e470d0a1a0a" ]]; then
    echo "clients-smoke: ${client} payload not a PNG (magic=${magic})" >&2
    exit 1
  fi
  echo "--- ${client}: OK ---"
done

echo "--- clients-smoke: all four legs green ---"
