import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorials: [
    'tutorials/index',
    'tutorials/install-cli',
    'tutorials/install-ui-walkthrough',
    'integrations/pack-demo-playbook',
  ],

  howto: [
    'howto/index',
    {
      type: 'category',
      label: 'Operations',
      collapsed: false,
      items: [
        'howto/troubleshoot-install',
      ],
    },
    {
      type: 'category',
      label: 'Client integrations',
      collapsed: false,
      items: [
        'integrations/claude-code',
        'integrations/claude-desktop',
        'integrations/gemini-cli',
        'integrations/hermes-agent',
        'integrations/openclaw',
        'integrations/openclaw-sidecar-research',
        'integrations/openclaw-upgrade-runbook',
        'integrations/openclaw-upstream-issue',
        'integrations/nemoclaw',
        'integrations/webhooks',
      ],
    },
    {
      type: 'category',
      label: 'Sidecars',
      items: [
        'SIDECAR-EXTENDING',
        'SIDECAR-LANGUAGES',
      ],
    },
  ],

  reference: [
    'reference/index',
    'PACKS',
    'integrations/SKILLS',
    'integrations/README',
    {
      type: 'category',
      label: 'Pack reference (per-pack)',
      link: {type: 'doc', id: 'reference/packs/index'},
      items: [
        {
          type: 'category',
          label: 'browser',
          items: [
            'reference/packs/browser/screenshot-url',
            'reference/packs/browser/interact',
          ],
        },
        {
          type: 'category',
          label: 'http',
          items: ['reference/packs/http/fetch'],
        },
        {
          type: 'category',
          label: 'doc',
          items: [
            'reference/packs/doc/ocr',
            'reference/packs/doc/parse',
          ],
        },
        {
          type: 'category',
          label: 'fs',
          items: [
            'reference/packs/fs/read',
            'reference/packs/fs/write',
            'reference/packs/fs/list',
            'reference/packs/fs/patch',
            'reference/packs/fs/delete',
          ],
        },
        {
          type: 'category',
          label: 'cmd',
          items: ['reference/packs/cmd/run'],
        },
        {
          type: 'category',
          label: 'git',
          items: [
            'reference/packs/git/commit',
            'reference/packs/git/diff',
            'reference/packs/git/log',
          ],
        },
        {
          type: 'category',
          label: 'language',
          items: [
            'reference/packs/language/python-run',
            'reference/packs/language/node-run',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Architecture Decisions',
      link: {type: 'generated-index', slug: '/adrs'},
      items: [{type: 'autogenerated', dirName: 'adrs'}],
    },
    {
      type: 'category',
      label: 'Project tracking',
      items: ['TASKS', 'MILESTONES', 'RELEASES'],
    },
  ],

  explanation: [
    'explanation/index',
    'SECURITY-HARDENING',
  ],
};

export default sidebars;
