import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorials: [
    'tutorials/index',
    'integrations/pack-demo-playbook',
  ],

  howto: [
    'howto/index',
    {
      type: 'category',
      label: 'Client integrations',
      collapsed: false,
      items: [
        'integrations/claude-code',
        'integrations/claude-desktop',
        'integrations/gemini-cli',
        'integrations/hermes-agent',
        'integrations/openclaw',
        'integrations/openclaw-sidecar-research',
        'integrations/openclaw-upgrade-runbook',
        'integrations/openclaw-upstream-issue',
        'integrations/nemoclaw',
        'integrations/webhooks',
      ],
    },
    {
      type: 'category',
      label: 'Sidecars',
      items: [
        'SIDECAR-EXTENDING',
        'SIDECAR-LANGUAGES',
      ],
    },
  ],

  reference: [
    'reference/index',
    'PACKS',
    'integrations/SKILLS',
    'integrations/README',
    {
      type: 'category',
      label: 'Architecture Decisions',
      link: {type: 'generated-index', slug: '/adrs'},
      items: [{type: 'autogenerated', dirName: 'adrs'}],
    },
    {
      type: 'category',
      label: 'Project tracking',
      items: ['TASKS', 'MILESTONES', 'RELEASES'],
    },
  ],

  explanation: [
    'explanation/index',
    'SECURITY-HARDENING',
  ],
};

export default sidebars;
